- name: Apply K8S Configuration
  hosts: node
  become: yes
  tasks:
    - name: Create new deployment
      command: kubectl apply -f /home/arafat/Deployment.yml
      register: result
      environment: 
        KUBECONFIG: /home/arafat/.kube/config

    - name: Create new service
      command: kubectl apply -f /home/arafat/Service.yml
      register: result
      environment: 
        KUBECONFIG: /home/arafat/.kube/config

