kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-test
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
      - name: devops-test
        image: taimumarfat/aws-mekong-devops
        imagePullPolicy: Always
        ports:
        - containerPort: 80