kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-test-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-test-2
  template:
    metadata:
      labels:
        app: devops-test-2
    spec:
      containers:
      - name: devops-test-2
        image: taimumarfat/aws-mekong-devops
        imagePullPolicy: Always
        ports:
        - containerPort: 80