kind: Service
apiVersion: v1
metadata:
  name: devops-test
  labels:
    app: devops-test
spec:
  ports:
    - port: 9090
      targetPort: 80
      nodePort: 31400
  selector:
    app: devops-test
  type: LoadBalancer
