kind: Service
apiVersion: v1
metadata:
  name: devops-test-2
  labels:
    app: devops-test-2
spec:
  ports:
    - port: 9050
      targetPort: 80
      nodePort: 30400
  selector:
    app: devops-test-2
  type: LoadBalancer
