kind: Service
apiVersion: v1
metadata:
  name: devops
  labels:
    app: devops
spec:
  ports:
    - port: 9080
      targetPort: 80
      nodePort: 31200
  selector:
    app: devops
  type: LoadBalancer
